**练习题（异常）**

** **

​    1．Java语言中异常的分类是哪项？   	B   (b)

​    A．运行时异常和异常

​    B．受检异常和非受检异常

​    C．错误和异常

​    D．错误和运行时异常

  

​    2．所有异常的父类是哪项？		D (a)

​    A. Throwable

​    B.  Error

​    C． RuntimeException

​    D． Exception

  

​    3．关于try...catch...finally结构，描述正确的是哪项？  （选两项）		AC(ac)

​    A.可以有多个catch

​    B．只能有一个catch

​    C．可以没有catch

​    D．finally必须有

   

​    4．下列属于非受检异常的是哪项？		C(d)

​    A．SQLException

​    B. IOException

​    C. NullPointerException

​    D．OutOfMemoryError

 

​    5．假设有自定义异常类ServiceException，那么抛出该异常的语句正确的是			B(b)

​    哪项？

​    A. raise ServiceException

​    B. throw new ServiceException()

​    C. throw ServiceException

​    D. throws ServiceException

​    6．在方法的声明中，要求该方法必须抛出异常时使用哪个关键字？		A(d)

​    A. throw

​    B. catch

​    C. finally

​    D. throws

​    

​    7．现有：		B(d)

​    1．  classNumber{

​    2.    public static void main(String []  aras)  {

​    3．   try  {

​    4.         System.out.print (Integer.parselnt ("forty"))；

​    5.         } catch (RuntimeException r)  { //父类

​    6.          System.out.print ("runtime");

​    7.      } catch  (NumberFormatExceptione)  { //子类

​    8.   system..ut.print("number");

​    9．     }

​    10．    }

​    11．  }

​    结果是什么？

​    A．  number

​    B．  runtime

​    C．  fortynumber

​    D．编译失败

​    

​    8．现有：		B(b)

​    9．  void topGo()  {

​    10．   try  {

​    11．   middleGo()；

​    12.     )  catch  (Exception e) {

​    13.    System.out.print("catch");

​    1 4．    }

​    15．  }

​    1 6. void middleGo()  throws Exception  {

​    17．    go()；

​    1 8.   system.out.print("late middle");

​    1 9．  }

​    2. void go()  throws Exception  {

​    21.   throw new Exception();

​    22．  }

如果调用 topGo () ,则结果为:		

A. late middle

B. catch

C. late middle catch

D. catch Iate middle

 

9.现有 			AC(ac)

    1. class Calc {

    2. public static void main(String [] args) {

    3. try {

    4. int x = Integer.parselnt("42a") ;

    5. //insert code here

    6. System.out.print ("oops");

    7. }

    8. }

    9. }

 下面哪两行分别插入到第五行，会导致输 "oops" ? (选两项)

 A. } catch (IllegalArgumentException e) {

 B. } catch (IllegalStateException c) {

 C. } catch (NumbelFormatException n) {

 D. } catch (ClassCastException c) {

   

 10.现有:		AC(bc)

    1. class Flow {

    2. public static void main(String [] args) t

    3. try {

 4 .              System. out .print("before") ;

 5 .                  doRiskyThing ( )  ;

    6.         System.out.print ("after") ;

    7.         }catch (Exception fe) {

    8.         System.out.print ("catch") ;

    9.         }

 10 .         System. out .println ( " done") ;

    11.   }

    12.   public static void doRiskyThing() throws Exception{

    13.   //this code returns unless it throws an Exception

​          }}

 可能会产生哪两项结果 ?（选两项）		

 A. before catch

 B. before after done

 C. before catch done

 D. before after catch

  11.现有:		C(c)

    1. class Birds { 
           public static void main (String []  args)  {
                try {
                     throw new Exception () ; 
                }catch (Exception e) { 
                    try { 
                         throw new Exception () ;
                    }  catch  (Exception e2)  { 
                         System.out.print ("inner  "); 
                    }       
                    System. out.print ("middle" ) ;    
                }    
                System.out.print ("outer") ;    
            } 
        }

   A. inner outer

   B. middle outer

   C. inner middle outer

   D .编译失败

​         

   12.现有：			B(b)

    class  Parser extends  Utilis { 
        public static void main (String []  args)  {  
              try  {  
                   System. out.print (new  Parser ( ) .getlnt ("42")) ;
              }  catch (NumberFormatException n){          
                  System.out .println ("NFExc" ) ;   
              } 
        } 
        int getlnt (String arg)  throws NumberFormatException{ 
              return Integer.parselnt (arg) ;  
         } 
    } 
    
     class Utils { 
         int getlnt (String arg)  {  
            return 42; 
         } 
     }

​    绐果为 :

​    A. NFExc

​    B. 42

​    C. 42NFExc

​    D．.编译失败

13．现有：		A(d)

​    1. class Parser extends Utils  (

​    2.public static void main (String[]  args)   {

​    3.try{

​                 System.out.print (newParser().getlnt("42"));

​    4.   } catch (Exception e)    {

​    5.      System.out.println("Exc");  }

​    6．    }

​    7.int getlnt (String arg)    throws   Exception  (

​    8.         return Integer.parselnt (arg);

​    9．   }

​    10. }

​    11. class Utils  {

​    12.          int getlnt (String arg)    {return42;  }

​    13．  }

​    结果为：

​    A. 42

​    B.Exc

​    C.42Exc

​    D．编译失败

 

   14．现有：	B

​    1．  classPropeller2  {

​    2.  pulolic static void main (String[]args)／／add code here?

​    3.   {  new Propeller2().topGo();  

​    }

​    5.void topGo()  ／／add code here?

​    6．   {   middleGo()； }

​    8.void middleGo()  ／／add code here?

​    9.   {   go();  System.out.println ("late middle"); }

​    10. void go() ／／add codehere?

​    12.   {throw new Exception();  }

​    13. }

​    为使代码通过编译，需要在哪一行加入声明throws Exception?

​    A．只在第11行

​    B．在第8行和第11行

​    C．在第5行、第8行和第11行

​    D．在第2行、第5行、第8行和第11行



1. 编写程序，要求输入若干整数，输入的同时计算前面输入各数的乘积，若乘积超过100000，则认为是异常，捕获并处理这个异常，输出信息。


2. 从控制台输入 5个整数，放入一整型数组，然后打印输出，要求：输入数据 为整数，要捕获Integer.parseInt()产生的异常，直至用户能够输入5个整数。（用户输入的不是整数则捕获异常）
3. 自定义异常类型 TrigonometricFunctionException extends Exception。并重写相应的构造器。

再写一个方法void sanjiao(int a,int b,int c)，判断三个参数作为三角形的边事否能构成一个三角形， 如果不能则抛出异常 TrigonometricFunctionException ，显示异常信息"a,b,c不能构成三角 形"，如果可以构成则显示三角形三个边长，在main方法中得到命令行输入的三个整数， 调用此方法，并捕获异常。



 参考答案 

​    1B

​    2A

​    3AC

​    4D

​    5B

​    6D

​    7D

​    8B

​    9 A C

​    10 B C

​    11 C

​    12 B

​    13 D
